IMB-99: quiz game
Imabulary/Imabulary pull request #100
Opened 2024-08-20 10:30 UTC by vladyslav-panchenko280

## Overview

Renew quiz game. Add quiz statuses and endpoint to update card quiz status. All business logic located in the front-end.

## Test cases

1. User click on "Start test". Quiz game is starting.
2. User choose one of options in pool, then make POST request to `api/quiz/learn`. In body user should pass cardId and choosen word

## Issue

closes [99](https://www.notion.so/Renew-quizes-31d92ff5550c48e7b5c8d9f29c92df07)

2024-08-20 16:31 UTC, DonAlexandro requested changes

2024-08-20 16:31 UTC, DonAlexandro commented on server/prisma/schema.prisma
> +  quizStatusName         String         @default("still_learning")
why do we have this field in Card table?

2024-08-20 16:31 UTC, DonAlexandro commented on server/prisma/schema.prisma
> +  textRepresentation String
what this field stands for?

2024-08-20 16:31 UTC, DonAlexandro commented on server/src/quiz/dto/quiz.dto.ts
> +export class QuizDto {
`QuizDTO`

2024-08-20 16:31 UTC, DonAlexandro commented on server/src/quiz/dto/quiz.dto.ts
> +    message: 'Flashcard is unavailable for feedback',
why feedback if it's a quiz

2024-08-20 16:31 UTC, DonAlexandro commented on server/src/quiz/quiz.controller.ts
> +  learnCard(@Body() asnwerDto: QuizDto) {
`learnCard` -> `learn`

2024-08-20 16:31 UTC, DonAlexandro commented on server/src/quiz/quiz.controller.ts
> +  learnCard(@Body() asnwerDto: QuizDto) {
`asnwerDto` -> `quizDto`

2024-08-20 16:31 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +        quizStatusName: isCorrect ? 'mastered' : 'still_learning',
let's make a dictionary for values like `mastered` and `still_learning` like we did for feedback categories

2024-08-20 17:32 UTC, vladyslav-panchenko280 commented on server/prisma/schema.prisma
> +  textRepresentation String
"name" is still_learining
"textRepresentation" is Still learning

2024-08-20 17:39 UTC, vladyslav-panchenko280 commented on server/src/quiz/quiz.service.ts
> +        quizStatusName: isCorrect ? 'mastered' : 'still_learning',
no sence, because only one quizStatus is available for card. In feedback categories, we need to create one more table to represent many-to-many relation. In this particular case, it's one-to-many relation

2024-08-20 17:48 UTC, vladyslav-panchenko280 commented on server/prisma/schema.prisma
> +  quizStatusName         String         @default("still_learning")
1. No sence, to create additional table. For example, QuizCard. It will cause logic dublication, and no more any functionality for QuizCard will provided
2. No sence store it in cardsOnSet, because we decided that it should be one state of card for all sets
3. To conclude, the most appropriate place to store quizStatus is Card table

P.S. current doc dedicated to this task is not relevant

2024-08-20 18:55 UTC, DonAlexandro commented on server/prisma/schema.prisma
> +  textRepresentation String
keep only the name, it's FE's job to put it in human-readable format

2024-08-20 18:57 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +        quizStatusName: isCorrect ? 'mastered' : 'still_learning',
it's not only about relations, it's also about 1 source of truth - the database where we store these values with unique ids which are the same for FE and BE so we won't have to update a lot of different enums, types, and staff across our whole system.

2024-08-20 18:59 UTC, DonAlexandro commented on server/prisma/schema.prisma
> +  quizStatusName         String         @default("still_learning")
Make it just a relation with QuizCardStatus

2024-08-22 09:57 UTC, vladyslav-panchenko280 commented on server/prisma/schema.prisma
> +  quizStatusName         String         @default("still_learning")
It already have relation

2024-08-22 10:09 UTC, DonAlexandro commented on server/prisma/schema.prisma
> +  quizStatusName         String         @default("still_learning")
okay, so just remove this field

2024-08-23 09:52 UTC, vladyslav-panchenko280 commented on server/prisma/schema.prisma
> +  quizStatusName         String         @default("still_learning")
quizStatusName is reference to quizStatus, it relation includes this field

2024-08-23 09:54 UTC, vladyslav-panchenko280 commented on server/src/quiz/quiz.service.ts
> +        quizStatusName: isCorrect ? 'mastered' : 'still_learning',
There is one source of truth - is database table with seeds. It store unique values like "mastered", "still_learinng" and so on.

2024-08-26 11:37 UTC, DonAlexandro requested changes

2024-08-26 11:37 UTC, DonAlexandro commented on server/src/quiz/quiz.controller.ts
> +    return this.quizService.saveResult(quizDto.cardId, quizDto.word);
send quizDto to `saveResult` method, do not separate params

2024-08-26 11:37 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +  async saveResult(cardId: string, word: string) {
expect to receive here `quizDto`

2024-08-26 11:37 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +    }
no reason to cover this peace in try-catch, if an error happens, it will be covered automatically

2024-08-26 11:37 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +  private findStatusId = (array: Record<string, string>[], statusName) => {
keep the same style for all functions:
`findStatusId = () => {}` -> `findStatusId() {}`

2024-08-26 11:37 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +  private findStatusId = (array: Record<string, string>[], statusName) => {
provide a valid type, not the `Record<string, string>`

2024-08-26 11:37 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +  async saveResult(cardId: string, word: string) {
name all services' methods same as controllers' ones:
`saveResult` -> `learn`

2024-08-28 13:07 UTC, DonAlexandro requested changes

2024-08-28 13:07 UTC, DonAlexandro commented on server/src/quiz/quiz.service.ts
> +        updatedAt: new Date(),
lets move strings like `mastered`, `still_learning` and `not_studied` in a separate constant object

2024-08-30 07:57 UTC, DonAlexandro requested changes

2024-08-30 07:57 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
> +            where: { name: 'not_studied' },
пропустив ще тут))

2024-08-30 08:52 UTC, vladyslav-panchenko280 commented on server/src/flashcards/flashcards.service.ts
> +            where: { name: 'not_studied' },
yeaap

2024-08-30 12:04 UTC, DonAlexandro approved these changes

2024-09-01 08:46 UTC, merged