IMB-114: Redesign home page
Imabulary/Imabulary pull request #110
Opened 2024-09-30 17:07 UTC by vladyslav-panchenko280

## Overview

The task involves redesigning the home page

## Issue

closes [114](https://www.notion.so/FE-Redesign-home-page-4b56961863664f0cb330130e33bc5795)

2024-09-30 17:19 UTC, DonAlexandro commented on mobile/lib/app/Home/presentation/home.dart
> +                        setsRepository.findAll(const Pagination(page: 1))),
format code using commas

2024-09-30 17:19 UTC, DonAlexandro commented on mobile/lib/app/Home/presentation/home.dart
>                      ),
please use `TypeSetting` - our internal component based on `Text` component with predefined text styles. Please replace it everywhere in the PR

2024-09-30 17:19 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/CardMenu/card_menu.dart
> +        ));
add comma for better formatting

2024-09-30 17:19 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +          ]),
same as above

2024-09-30 19:40 UTC, vladyslav-panchenko280 commented on mobile/lib/app/Home/presentation/home.dart
> +                        setsRepository.findAll(const Pagination(page: 1))),
but it already has comma on 71 line

2024-09-30 19:48 UTC, vladyslav-panchenko280 commented on mobile/lib/app/Home/presentation/home.dart
>                      ),
fixed

2024-09-30 19:48 UTC, vladyslav-panchenko280 commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +          ]),
but it already has comma on 69 line

2024-10-01 10:16 UTC, DonAlexandro requested changes

2024-10-01 10:16 UTC, DonAlexandro commented on mobile/lib/app/Home/presentation/home.dart
> +                        setsRepository.findAll(const Pagination(page: 1))),
try to do like this: setsRepository.findAll(const Pagination(page: 1),),)
in such way code will be easier to read, because it won't be listed in 1 line

2024-10-01 10:16 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +          ]),
put it also after `]`

2024-10-01 10:16 UTC, DonAlexandro commented on mobile/lib/app/Home/presentation/home.dart
>                      ),
good, and now also use `textVariant` property so you won't have to redefine styles everytime

2024-10-01 13:48 UTC, DonAlexandro commented
1. When I click on "Create your first set" or "My Sets", nothing is happening
2. When I click on "Take a quiz", nothing is happening

2024-10-02 08:06 UTC, vladyslav-panchenko280 commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +          ]),
you already fixed it

2024-10-02 08:07 UTC, vladyslav-panchenko280 commented on mobile/lib/app/Home/presentation/home.dart
>                      ),
you already fixed it

2024-10-02 08:07 UTC, vladyslav-panchenko280 commented on mobile/lib/app/Home/presentation/home.dart
> +                        setsRepository.findAll(const Pagination(page: 1))),
you already fixed it

2024-10-08 19:22 UTC, DonAlexandro requested changes

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/assets/images/quiz_picture.png
Delete this image

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/assets/images/card_example_flower.png
delete this image

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/FlashCard/domain/quiz_status.dart
> +class QuizStatuses with _$QuizStatuses {
it's `QuizStatus`, because type represents only 1 record

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/quick_actions.dart
please use `mobile/lib/widgets/list_item.dart`, because it has all styles defined already, but u can extend it, so it fits your needs
check an example how to use the component here: `mobile/lib/app/Home/widgets/FlashcardListItem/flashcard_list_item.dart` and here `mobile/lib/app/Home/widgets/flash_cards_list.dart`

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/presentation/home.dart
> +                QuickActions(setsRepository: setsRepository),
use ListItem instead of creating custom component

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/CardMenu/card_menu.dart
you probably won't need this component once you remove `QuickActions`

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +      {super.key, required this.wallet, required this.flashcards});
put a comma after `flashcards`

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +                    ),
bold style is already included into headlineLarge style

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +                    ),
same as above

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +            ),
same as above

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +            ),
same as above

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +                  fontWeight: FontWeight.bold,
use `TextVariant.headlineLarge`

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +          ),
use `TypeSetting`

2024-10-08 19:22 UTC, DonAlexandro commented on mobile/lib/app/Home/widgets/home_app_title.dart
> +            ),
same as above

2024-10-21 12:42 UTC, DonAlexandro approved these changes

2024-10-21 12:42 UTC, merged