IMB-296: [BE] - Implement user deletion logic
Imabulary/Imabulary pull request #113
Opened 2024-10-23 08:59 UTC by vladyslav-panchenko280

## Overview

Implemented user deletion with removal of associated resources (images, audio, feedback). Updated dependencies for wallet, flashcards, sets, and feedback to enable automatic resource deletion at the Prisma level.

## Test cases

1. Using Postman try send DELETE request (remove guard and insert userId manually in code in local environment) to /users endpoint

## Issue

closes [IMB-296](https://www.notion.so/Phase-1-Let-user-delete-his-entire-data-from-the-app-ed9d997bd9a64aa0a4aa1ce50c1990ee)

2024-10-23 14:40 UTC, DonAlexandro requested changes

2024-10-23 14:40 UTC, DonAlexandro commented on server/openapi/components/schemas/user/delete-user-dto.yaml
you don't need the DTO for this endpoint, because you can take all information about the user from the request, check `server/src/flashcards/flashcards.controller.ts`

2024-10-23 14:40 UTC, DonAlexandro commented on server/src/users/dto/user.dto.ts
> +}
same as above

2024-10-23 14:40 UTC, DonAlexandro commented on server/src/users/users.service.ts
> +    });
please use the `findOne` method, and extend it, if you need more than just `where`

2024-10-23 14:40 UTC, DonAlexandro commented on server/src/users/users.service.ts
> +    };
Let's just return `true` indicating that deletion was successful and display this message on FE only, if needed

2024-10-23 14:40 UTC, DonAlexandro commented on server/src/users/users.service.ts
> +  async delete(deleteUserDto: DeleteUserDTO) {
you don't need the whole DTO, if you just need 1 property

2024-10-23 14:40 UTC, DonAlexandro commented on server/src/users/users.service.ts
> +      });
create a separate method called `update` inside `feedback.service`, add a parameter called `strategy`, this parameter will be nullable and take `single` as a default value, but it also can take `many` to update many records. Use the new method here and provide a `many` strategy and all other required params

2024-10-24 08:03 UTC, vladyslav-panchenko280 commented on server/src/users/users.service.ts
> +      });
In this case we will have problem with update. Update should has id for feedback, it required. For updateMany we will define `where` as we want. So, i propose create two methods, update and updateMany

2024-10-24 12:01 UTC, DonAlexandro commented on server/src/users/users.service.ts
> +    };
just `return true` without object

2024-10-24 12:01 UTC, DonAlexandro commented on server/src/users/users.service.ts
> +      });
okay, then let's do it through condition, I provide a pseudo-code for example:
```
if (id) update
if (where) updateMany
if (!id && !where) throw 
```

2024-10-24 16:24 UTC, vladyslav-panchenko280 reviewed
"if (id) update
if (where) updateMany
if (!id && !where) throw" 

I think, it will not work correct, if we want to specify any fields despite an id
My opinion - let's leave them in two apart functions like now

2024-10-24 16:28 UTC, DonAlexandro commented
> "if (id) update if (where) updateMany if (!id && !where) throw"
> 
> I think, it will not work correct, if we want to specify any fields despite an id My opinion - let's leave them in two apart functions like now

okay, let's leave it as is now

2024-10-25 07:29 UTC, merged