IMB-101 Renew quizes
Imabulary/Imabulary pull request #122
Opened 2024-11-21 12:41 UTC by AndriiBoichuk

## Overview

- Renew quizes

## Test cases

- Pass quizzes
- Open set screen
- Open Quiz Results screen

## Screenshots / Screen recordings

https://github.com/user-attachments/assets/53396db4-701a-4d50-840c-c4bc1ea7ab24

## Issue

closes [IMB-101](https://www.notion.so/FE-Implement-new-design-480cb6bd835c4aed91815d21e55711c3?pvs=4)

2024-11-21 19:57 UTC, DonAlexandro requested changes

2024-11-21 19:57 UTC, DonAlexandro commented on mobile/lib/app/Quiz/data/quiz_repository.dart
> +  }
do not duplicate the method u have right above

2024-11-21 19:57 UTC, DonAlexandro commented on mobile/lib/app/Quiz/data/quiz_repository.dart
> +  Future<void> updateQuizAnswer({required String cardId, required String word}) async {
let's create `UpdateQuizAnswerDTO` and use the `toJson` method instead of serializing it manually

2024-11-21 19:57 UTC, DonAlexandro commented on mobile/lib/app/Quiz/presentation/results/widgets/result_item_widget.dart
you don't need this component, as we already have a generic one: `mobile/lib/widgets/list_item.dart`
just slightly modify it for your purposes

2024-11-21 19:57 UTC, DonAlexandro commented on mobile/lib/app/Set/widgets/flashcard_item_widget.dart
same as above

2024-11-21 20:00 UTC, DonAlexandro commented
@AndriiBoichuk and 2 bugs that I found:
1. When we click on the "Fix my mistakes" button, the quiz starts with all flashcards in the set, but there should be only those flashcards, that the user has chosen incorrectly in the previous attempt
2. When we click on the "My Sets" list item on the home page, the system redirects us to the profile flashcards view, but it should redirect to the profile sets view

2024-11-22 08:31 UTC, AndriiBoichuk commented on mobile/lib/app/Quiz/presentation/results/widgets/result_item_widget.dart
`mobile/lib/widgets/list_item.dart` uses ListTile that doesn't allow us to change the border width or color

2024-11-22 10:48 UTC, AndriiBoichuk commented on mobile/lib/app/Set/widgets/flashcard_item_widget.dart
mobile/lib/widgets/list_item.dart uses ListTile that doesn't allow us to change the border width or color

2024-11-22 12:25 UTC, DonAlexandro approved these changes

2024-11-22 12:48 UTC, merged