IMB-68: feat. text-to-speech
Imabulary/Imabulary pull request #95
Opened 2024-07-30 15:30 UTC by vladyslav-panchenko280

## Overview

Text to speech feature

## Issue

closes [68](https://www.notion.so/BE-Implement-requirements-b79d2a94b4a44d93a6a8105bb0a25b7b?pm=c)

2024-07-31 13:29 UTC, DonAlexandro commented
I think we don't need text-to-speech as a separate API. Just generate the sound during flashcard generation and save it somewhere (Firebase Storage?) so we can play it later on the frontend

2024-07-31 13:30 UTC, DonAlexandro requested changes

2024-07-31 13:30 UTC, DonAlexandro commented on server/src/text-to-speech/text-to-speech.service.ts
> +export class TextToSpeechService implements OnModuleInit {
let's name it `SoundService`

2024-08-04 14:01 UTC, DonAlexandro requested changes

2024-08-04 14:01 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
> +  }
remove this method and do everything inside the `scan` method.
if you want think, that `scan` method is too big, we can split into chunks using Template Method pattern

2024-08-04 14:01 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
> +      await imageFile.delete();
add deletion of audio file as well

2024-08-05 07:17 UTC, vladyslav-panchenko280 commented on server/src/flashcards/flashcards.service.ts
> +  }
Template method isn't appropriate for this. Scan method is full-fledged method, which can't be splitted into AudioScanner and FileScanner, because both actions needed for postgres Card creation (AudioScanner will depend on FileScanner). I see this method rather as Chain of Responsibility. We can leave solidity of the method for the present

2024-08-05 07:35 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
> +  }
Oh, yeah, u r right, Chain of Responsibilities is better, I just thought about some trimmed version of Template Method that I used to use on my previous projects, but nvm
can u put TODO on top of this method so we won't forget to refactor it?

2024-08-05 07:35 UTC, DonAlexandro approved these changes

2024-08-05 09:53 UTC, merged