IMB-97: feedback with categories
Imabulary/Imabulary pull request #98
Opened 2024-08-09 11:30 UTC by vladyslav-panchenko280

## Overview

[Feedback about generated flashcard](https://www.notion.so/Docs-cc934849c14e4db29697d5f2ba5cc8da?p=9604249c64f64b74ab5685355d8c8b57&pm=s)

## Issue

closes [97](https://www.notion.so/9890d55037984940ad4e514976be9fb6?v=ba4ddb1cfe9f442ba8f2326ef9b56fb2&p=1d3e0765a5054d95be47bbb437f27efb&pm=s)

2024-08-09 15:42 UTC, DonAlexandro requested changes

2024-08-09 15:42 UTC, DonAlexandro commented on server/openapi/components/schemas/card/card.yaml
> +    nullable: true
do we really need it in the API response, won't it expose our internal staff?

2024-08-09 15:42 UTC, DonAlexandro commented on server/openapi/components/schemas/card/feedback-category.yaml
> +    example: "Translation of the word on the photo"
do not hardcode it
we'll add new languages in the future, moreover, we'll be translating the app on the frontend only

2024-08-09 15:42 UTC, DonAlexandro commented on server/openapi/components/schemas/card/dislike-flashcard-dto.yaml
>        textFeedback:
@vladyslav-panchenko280 I suggest naming this column just text, as the table is already called “Feedback”, so no reason to be so precise :)

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/dto/feedback.dto.ts
> +  }
this is redundant, as u r already providing the message down below

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/dto/feedback.dto.ts
> +class EitherCategoryIdOrTextFeedbackConstraint
move this decorator out of dto file and put it inside `decorators` folder

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/flashcards.controller.ts
> +    }
no reason to add this validation, because it's enabled globally

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/flashcards.controller.ts
> +  }
move this to a separate `feedback` module

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
> +            'Card soft deleted and removed from sets successfully. Thank you for your feedback!',
don't mention internal staff like soft delete in message that are sent via the API.
"Card was deleted successfully. Thank you for your feedback!" is enough

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
> +  }
move this to a separate `feedback` module

2024-08-09 15:42 UTC, DonAlexandro commented on server/src/flashcards/flashcards.service.ts
>        const feedback = await prisma.feedback.create({
move creation of feedback to a separate `feedback` module

2024-08-13 09:39 UTC, vladyslav-panchenko280 commented on server/src/flashcards/dto/feedback.dto.ts
> +class EitherCategoryIdOrTextFeedbackConstraint
it relates only to feedback, so I just split into files

2024-08-13 16:50 UTC, DonAlexandro requested changes

2024-08-13 16:50 UTC, DonAlexandro commented on server/prisma/schema.prisma
> +  feedbackCategory   FeedbackCategory? @relation(fields: [feedbackCategoryId], references: [id])
remove `feedback` prefix

2024-08-13 16:50 UTC, DonAlexandro commented on server/src/feedback/flashcards.controller.ts
> +  @Get('/feedback-categories')
name it just `categories`

2024-08-13 16:50 UTC, DonAlexandro commented on server/src/flashcards/flashcards.controller.ts
> +    await validate(dislikeFlashcardDto);
you don't need to validate DTO here, it must be validated automatically by global `ValidationPipe`

2024-08-16 07:40 UTC, DonAlexandro requested changes

2024-08-16 07:40 UTC, DonAlexandro commented on server/src/feedback/flashcards.controller.ts
> +  @Get('/feedback')
`categories` not a feedback, feedback is a controller)

2024-08-16 10:16 UTC, DonAlexandro approved these changes

2024-08-16 10:17 UTC, merged